version: '3.2'

services:
    mysql:
        image: "mysql:5.7.32"
        command: --default-authentication-plugin=mysql_native_password
        environment:
            MYSQL_DATABASE: "${MYSQL_DATABASE}"
            MYSQL_ROOT_PASSWORD: "${MYSQL_PASSWORD}"
            MYSQL_ROOT_HOST: "%"
            MYSQL_USER: "${MYSQL_USER}"
            MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
            TZ: Asia/Taipei
        restart: unless-stopped

    ais3:
        build: ./
        ports:
            - 3000:3000
        depends_on:
            - mysql
        environment:
            NODE_ENV: dev
            MYSQL_HOST: mysql
            MYSQL_DATABASE: "${MYSQL_DATABASE}"
            MYSQL_USER: "${MYSQL_USER}"
            MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
            SESSION_SECRET: sdfsdfsdf
        restart: unless-stopped