version: '3.2'

services:
    mysql:
        image: "mysql:5.7.32"
        command: --default-authentication-plugin=mysql_native_password
        ports:
            - 3306:3306
        environment:
            MYSQL_DATABASE: "${MYSQL_DATABASE}"
            MYSQL_ROOT_PASSWORD: "${MYSQL_PASSWORD}"
            MYSQL_ROOT_HOST: "%"
            MYSQL_USER: "${MYSQL_USER}"
            MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
            TZ: Asia/Taipei
        restart: unless-stopped